/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Booking.java
 *
 * Created on 29 Dec, 2013, 1:59:37 PM
 */

package flightbooking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;


/**
 *
 * @author Karan
 */
public class Booking extends javax.swing.JFrame {
    int passcount=0;

    /** Creates new form Booking */
    public Booking() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormSignUp = new javax.swing.JFrame();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        FormBook = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        FormHistory = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jTextField3 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        FormSignUp.setMinimumSize(new java.awt.Dimension(360, 435));
        FormSignUp.setResizable(false);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField8.setBorder(javax.swing.BorderFactory.createTitledBorder("User Id"));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField9.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Number"));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14));
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(4);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NEW USER ACCOUNT");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("CREATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField11.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        javax.swing.GroupLayout FormSignUpLayout = new javax.swing.GroupLayout(FormSignUp.getContentPane());
        FormSignUp.getContentPane().setLayout(FormSignUpLayout);
        FormSignUpLayout.setHorizontalGroup(
            FormSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(FormSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(FormSignUpLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(FormSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        FormSignUpLayout.setVerticalGroup(
            FormSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormSignUpLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        FormSignUpLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordField1, jTextField8});

        FormBook.setMinimumSize(new java.awt.Dimension(630, 520));
        FormBook.setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setText("BOOKINGS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NEW FLIGHT BOOKING");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Source City"));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBox2.setBorder(javax.swing.BorderFactory.createTitledBorder("Desitination City"));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField2.setText("yyyy/mm/dd");
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Travel Date"));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jComboBox2, jTextField2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton4, jComboBox1, jComboBox2, jTextField2});

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Flight Id:"));
        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder("Seat Fair"));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Company"));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Duration"));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton7.setText("ADD PASSENGER");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTextField18.setEditable(false);
        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField18.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Seats"));

        jTextField19.setEditable(false);
        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField19.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Seats"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField18, jTextField19, jTextField4, jTextField5, jTextField6, jTextField7});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField4, jTextField5, jTextField6});

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24));
        jButton8.setText("BOOK");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24));
        jButton9.setText("RESET");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormBookLayout = new javax.swing.GroupLayout(FormBook.getContentPane());
        FormBook.getContentPane().setLayout(FormBookLayout);
        FormBookLayout.setHorizontalGroup(
            FormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormBookLayout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        FormBookLayout.setVerticalGroup(
            FormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormBookLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        FormHistory.setMinimumSize(new java.awt.Dimension(457, 260));
        FormHistory.setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FLIGHT BOOKING HISTORY");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton10.setText("New Booking");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton11.setText("EXIT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Booking Id:"));
        jList2.setModel(new DefaultListModel());
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList2);

        jTextField3.setEditable(false);
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Travel Time"));

        jTextField12.setEditable(false);
        jTextField12.setBorder(javax.swing.BorderFactory.createTitledBorder("Flight Id"));

        jTextField13.setEditable(false);
        jTextField13.setBorder(javax.swing.BorderFactory.createTitledBorder("Passenger"));

        jTextField14.setEditable(false);
        jTextField14.setBorder(javax.swing.BorderFactory.createTitledBorder("Seat Number"));

        jTextField15.setEditable(false);
        jTextField15.setBorder(javax.swing.BorderFactory.createTitledBorder("Travel Date"));

        jTextField16.setEditable(false);
        jTextField16.setBorder(javax.swing.BorderFactory.createTitledBorder("Source"));

        jTextField17.setEditable(false);
        jTextField17.setBorder(javax.swing.BorderFactory.createTitledBorder("Destination"));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton12.setText("CANCEL");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormHistoryLayout = new javax.swing.GroupLayout(FormHistory.getContentPane());
        FormHistory.getContentPane().setLayout(FormHistoryLayout);
        FormHistoryLayout.setHorizontalGroup(
            FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FormHistoryLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField13)
                            .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(FormHistoryLayout.createSequentialGroup()
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormHistoryLayout.createSequentialGroup()
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FormHistoryLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField12, jTextField14, jTextField15, jTextField16, jTextField17, jTextField3});

        FormHistoryLayout.setVerticalGroup(
            FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormHistoryLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FormHistoryLayout.createSequentialGroup()
                        .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField13)))
                    .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FormHistoryLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField12, jTextField14, jTextField15, jTextField16, jTextField17, jTextField3});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Flight Ticket Booking<br><center>User Login");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("User Id:"));

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Password:"));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jButton3.setText("Log In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setText("Sign Up");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flightbooking/plane.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                .addGap(98, 98, 98))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

            String userid=jTextField1.getText();
            String pass=new String(jPasswordField2.getPassword());

            String qry="select password from users where userid='"+userid+"';";

            ResultSet rs=stmt.executeQuery(qry);

            if(rs.next()==true)
            {
                String password=rs.getString("password");

                if(pass.equals(password))
              {

                 jButton9.doClick();
                 FormBook.setVisible(true);
                 dispose();


              }
              else
              JOptionPane.showMessageDialog(this,"Wrong Password");

            }
            else
            JOptionPane.showMessageDialog(this,"User id doen't exists");





       }catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        FormSignUp.setVisible(true);

        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jTextField11.setText(null);
        jPasswordField1.setText(null);
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

        DefaultListModel model=(DefaultListModel)jList2.getModel();
        model.removeAllElements();
        jList2.setModel(model);

        jTextField3.setText(null);
        jTextField12.setText(null);
        jTextField13.setText(null);
        jTextField14.setText(null);
        jTextField15.setText(null);
        jTextField16.setText(null);
        jTextField17.setText(null);
        jButton12.setEnabled(false);

       String userid=jTextField1.getText();
       String qry="select bookingid from bookings where userid='"+userid+"';";
       ResultSet rs=stmt.executeQuery(qry);
        while(rs.next()==true)
        {
            model.addElement(rs.getString("bookingid"));

        }


        FormBook.setVisible(false);
        FormHistory.setVisible(true);

       }catch(Exception e) {
            JOptionPane.showMessageDialog(FormBook,e.getMessage());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

        String userid=jTextField8.getText();
        String pass=new String(jPasswordField1.getPassword());
        String name=jTextField11.getText();
        String ph=jTextField9.getText();
        String email=jTextField10.getText();
        String address=jTextArea1.getText();

        if((userid.isEmpty() && pass.isEmpty() && name.isEmpty() && ph.isEmpty()
          && email.isEmpty() && address.isEmpty())==false)
        {
            String qry1="select * from users where userid='"+userid+"';";
            ResultSet rs1=stmt.executeQuery(qry1);

            if(rs1.next()==false)
            {
              String qry2="insert into users values('"+userid+"','"+name+"','"+pass+"','"+ph+"','"+email+"','"+address+"');";
              stmt.executeUpdate(qry2);
              JOptionPane.showMessageDialog(FormSignUp,"Account created");
              FormSignUp.setVisible(false);
              rs1.close();
            }
            else
            JOptionPane.showMessageDialog(FormSignUp,"User Id already exists");
        }
else
  JOptionPane.showMessageDialog(FormSignUp,"Please check input fields");

}catch(Exception e) {
            JOptionPane.showMessageDialog(FormSignUp,e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton13.doClick();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();


            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();

            String qry1="select distinct source from flights;";
            ResultSet rs=stmt.executeQuery(qry1);
            while(rs.next()==true)
            {
                String src=rs.getString("source");
                jComboBox1.addItem(src);
            }
            rs.close();


            String qry2="select distinct destination from flights;";
            ResultSet rs2=stmt.executeQuery(qry2);
            while(rs2.next()==true)
            {
                String src=rs2.getString("destination");
                jComboBox2.addItem(src);
            }
            rs2.close();

            jComboBox1.setSelectedIndex(-1);
            jComboBox2.setSelectedIndex(-1);

            jTextField2.setText("yyyy/mm/dd");
            jTextField18.setText(null);
            jTextField19.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);

            jButton7.setEnabled(false);
            jButton8.setEnabled(false);

            DefaultListModel model=(DefaultListModel)jList1.getModel();
            model.removeAllElements();
            jList1.setModel(model);

            DefaultTableModel dlm=(DefaultTableModel)jTable1.getModel();
            int rows=dlm.getRowCount();
              if(rows>0)
              {
                   for(int i=0;i<rows;i++)
                    {
                       dlm.removeRow(0);
                    }
              }
               jTable1.setModel(dlm);





      }catch(Exception e) {
            JOptionPane.showMessageDialog(FormBook,e.getMessage());
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jButton3.doClick();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

            String src=(String)jComboBox1.getSelectedItem();
            String dest=(String)jComboBox2.getSelectedItem();
            String date=jTextField2.getText();

            jTextField18.setText(null);
            jTextField19.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);
            DefaultListModel model=(DefaultListModel)jList1.getModel();
            model.removeAllElements();
            DefaultTableModel dlm=(DefaultTableModel)jTable1.getModel();
            int rows=dlm.getRowCount();
              if(rows>0)
              {
                   for(int i=0;i<rows;i++)
                    {
                       dlm.removeRow(0);
                    }
              }
            jList1.setModel(model);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);


            if(src!=null && dest!=null && date.isEmpty()==false)
            {
                String qry1="select datediff('"+date+"',curdate()) as chk;";
                ResultSet rs1=stmt.executeQuery(qry1);

                if(rs1.next()==true)
                {
                    int check=rs1.getInt("chk");
                    rs1.close();

                    if(check>0)
                    {

                        String qry2="select flightid from flights where source='"+src+"' and destination='"+dest+"' and date='"+date+"';";
                        ResultSet rs2=stmt.executeQuery(qry2);
                       int count=0;
                       while(rs2.next()==true)
                       {
                           model.addElement(rs2.getString("flightid"));
                           count++;
                       }
                       JOptionPane.showMessageDialog(FormBook,count+" Flights found");

                    }
                    else
                    JOptionPane.showMessageDialog(FormBook,"Booking date must be greater than today's date");

                }

            }
            else
            JOptionPane.showMessageDialog(FormBook,"Please check input fields");


       }catch(Exception e) {
            JOptionPane.showMessageDialog(FormBook,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
 try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

            String flightid=(String)jList1.getSelectedValue();
            passcount=0;

            if(flightid!=null)
            {
            String qry1="select * from flights where flightid="+flightid;
            ResultSet rs1=stmt.executeQuery(qry1);

            int totseats=0,filled=0,availseats=0;
            DefaultTableModel dlm=(DefaultTableModel)jTable1.getModel();
            int rows=dlm.getRowCount();
              if(rows>0)
              {
                   for(int i=0;i<rows;i++)
                    {
                       dlm.removeRow(0);
                    }
              }
               jTable1.setModel(dlm);
               jButton7.setEnabled(false);
               jButton8.setEnabled(false);

            if(rs1.next()==true)
            {
                totseats=rs1.getInt("seats");
                jTextField19.setText(""+totseats);
                jTextField4.setText(rs1.getString("time"));
                jTextField5.setText(rs1.getString("price"));
                jTextField6.setText(rs1.getString("company"));
                jTextField7.setText(rs1.getString("duration"));

            }
            rs1.close();

            String qry2="select count(bookid) as filled from flight"+flightid+";";
            ResultSet rs2=stmt.executeQuery(qry2);

            if(rs2.next()==true)
            {
                filled=rs2.getInt("filled");
                availseats=totseats-filled;
                jTextField18.setText(""+availseats);
            }
            rs2.close();

            if(availseats>0)
            {
                jButton7.setEnabled(true);
            }
            else
            jButton7.setEnabled(false);

      }
       }catch(Exception e) {
            JOptionPane.showMessageDialog(FormBook,e.getMessage());
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      passcount++;
      int availseats=Integer.parseInt(jTextField18.getText());

      DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
      model.addRow(new Object[]{});

      jButton8.setEnabled(true);

      if(passcount==availseats)
      {
          jButton7.setEnabled(false);
      }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 try {

        Class.forName("java.sql.DriverManager");
        Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
        Statement stmt=(Statement)con.createStatement();

        String flightid=(String)jList1.getSelectedValue();
        String userid=jTextField1.getText();
        double amt=Double.parseDouble(jTextField5.getText());

         int[] bookid,seatno;
         bookid=new int[passcount];
         seatno=new int[passcount];

        TableCellEditor cellEditor = jTable1.getCellEditor();

        if(cellEditor!=null)
        {
            jTable1.getCellEditor().stopCellEditing();
        }

        int nullcount=0;
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int rows=model.getRowCount();
        int i=0,j=0;
        for(i=0;i<=rows-1;i++)
        {
        for(j=0;j<=1;j++)
         {
            String temp = (String) jTable1.getValueAt(i, j);
            if(temp==null)
            {
                nullcount++;
            }

         }
       }

        if(nullcount>0)
        {
            JOptionPane.showMessageDialog(FormBook,"Invalid passenger Details");
        }
 else{
        for(int k=0;k<=passcount-1;k++)
        {
             String pname=(String)jTable1.getValueAt(k,0);
             String age=(String)jTable1.getValueAt(k,1);

             String qry3="insert into  bookings(flightid,userid,passenger,age,amount) values"
                     + "('"+flightid+"','"+userid+"','"+pname+"',"+age+","+amt+");";

             stmt.executeUpdate(qry3);

             String qry4="select bookingid from bookings order by bookingid desc";
             ResultSet rs1=stmt.executeQuery(qry4);

             if(rs1.next()==true)
             {
                 bookid[k]=rs1.getInt("bookingid");
                 rs1.close();
             }
        }

        String qry5="select seatno from flight"+flightid+" where bookid is null";

            ResultSet rs2=stmt.executeQuery(qry5);
            int count=0;
            while(rs2.next()==true)
            {
                count++;

                seatno[count-1]=rs2.getInt("seatno");
                if(count==passcount)
                break;
            }

            String output="Booking Successfull\nFlight Id:"+flightid;
      for(int k=0;k<=passcount-1;k++)
      {
          String qry6="update flight"+flightid+" set bookid="+bookid[k]+" where seatno="+seatno[k]+";";
          String qry7="update bookings set seatno="+seatno[k]+" where bookingid="+bookid[k]+";";
          stmt.executeUpdate(qry6);
          stmt.executeUpdate(qry7);

          output+="\nBooking Id: "+bookid[k]+" , Seat No: "+seatno[k];

      }
            amt=amt*passcount;
            output+="\nAmount: Rs "+amt;

            JOptionPane.showMessageDialog(FormBook,output);
            jButton9.doClick();

     }


}catch(Exception e) {
            JOptionPane.showMessageDialog(FormBook,e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
 try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

            String bookid=(String)jList2.getSelectedValue();
            String qry="select * from bookings,flights where bookings.flightid=flights.flightid and bookingid="+bookid+";";

            ResultSet rs=stmt.executeQuery(qry);
            String date="";
            if(rs.next()==true)
            {
                jTextField12.setText(rs.getString("flightid"));
                jTextField16.setText(rs.getString("source"));
                jTextField17.setText(rs.getString("destination"));
                jTextField14.setText(rs.getString("seatno"));
                date=rs.getString("date");
                jTextField15.setText(date);
                jTextField3.setText(rs.getString("time"));
                jTextField13.setText(rs.getString("passenger"));
            }

    String qry1="select datediff('"+date+"',curdate()) as chk;";
                ResultSet rs1=stmt.executeQuery(qry1);

                if(rs1.next()==true)
                {
                    int check=rs1.getInt("chk");
                    rs1.close();

                    if(check>0)
                    {
                        jButton12.setEnabled(true);
                    }
                    else
                        jButton12.setEnabled(false);


                }

       }catch(Exception e) {
            JOptionPane.showMessageDialog(FormHistory,e.getMessage());
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 try {

            Class.forName("java.sql.DriverManager");
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/flight","root","school");
            Statement stmt=(Statement)con.createStatement();

        String bookid=(String)jList2.getSelectedValue();
        String flightid=jTextField12.getText();
        String seatno=jTextField14.getText();

        String qry="delete from bookings where bookingid="+bookid+";";
        String qry1="update flight"+flightid+" set bookid=NULL where seatno="+seatno+";";
        stmt.executeUpdate(qry);
        stmt.executeUpdate(qry1);

        JOptionPane.showMessageDialog(FormHistory,"Booking Canceled");



        jButton5.doClick();



       }catch(Exception e) {
            JOptionPane.showMessageDialog(FormHistory,e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FormBook;
    private javax.swing.JFrame FormHistory;
    private javax.swing.JFrame FormSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
